#%RAML 1.0 Trait
headers:
  client_id:
    type: string
  client_secret:
    type: string
responses:
  401:
    description: Unauthorized, The client_id or client_secret are not valid or the client does not have access.
  429:
    description: The client used all of it's request quota for the current period.
  500:
    description: An error ocurred, see the specific message (Only if it is a WSDL enpoint).
  503:
    description: Contracts Information Unreachable.