#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: |
  This API supports OAuth 2.0 for authenticating all API requests.
describedBy:
  headers:
    authorization:
      description: |
         Used to send a valid OAuth 2 access token. Do not use with the "access_token" query
         string parameter.
      type: string
  responses:
    400:
      description: Invalid token.
    401:
      description: |
        Unauthorized or Connection error when connecting to the authorization server.
    403:
      description: |
        Forbidden, invalid client application credentials.
    500:
      description: |
        Bad response from authorization server, or WSDL SOAP Fault error.
settings:
  #Change http to https in URI's!
  authorizationUri: <<INSERT_OAUTH2_CLOUDHUB_APPLICATION_DOMAIN_NAME>>authorize
  accessTokenUri: <<INSERT_OAUTH2_CLOUDHUB_APPLICATION_DOMAIN_NAME>>access_token
  authorizationGrants: implicit